-- migrate:persona-indexes
-- DatabaseMigrator builds these indexes one at a time with
-- CREATE UNIQUE INDEX CONCURRENTLY, outside a transaction:
--   handled_mentions_persona_mention
--   work_queue_active_persona_mention (queued, claimed)
--   publish_requests_active_persona_mention
--     (queued, retry, publishing, published)
--   artifact_tags_active_persona_uri_label
-- It also creates non-unique persona/time indexes for token, web, and Scout
-- accounting. Invalid remnants from an interrupted concurrent build are
-- dropped concurrently before retry.
